kaggle-classification/README.md
kaggle-classification/requirements.txt
kaggle-classification/setup.py
kaggle-classification/trainer/wikidata.py

tf.contrib is deprecated. switch to tflearn

Convert contrib to tflearn VocabularyProcessor

---

kaggle-classification/README.md
kaggle-classification/bin/ls-jobs
kaggle-classification/bin/run
kaggle-classification/bin/run_local
kaggle-classification/trainer/model.py

* `run.sh` -> `bin/run`
* `run_local.sh` -> `bin/run_local`
* Add `bin/ls-jobs` to list all the jobs run on ml-engine today

Add bin directory

---

kaggle-classification/bin/run
kaggle-classification/config.yaml
kaggle-classification/trainer/model.py

Also updates cloud job names to include username. Adds a few comments we'll eventually want to remove, but are helpful for now while we all explore this.

Use GPUs by cloud jobs

---

kaggle-classification/bin/run
kaggle-classification/trainer/model.py

So we no longer write model-specific files to two places

Combine the job_dir and the saved_model_dir

---

kaggle-classification/.gitignore
kaggle-classification/bin/run_keras.sh
kaggle-classification/keras_trainer/cnn_with_attention.py
kaggle-classification/keras_trainer/custom_metrics.py
kaggle-classification/keras_trainer/model.py
kaggle-classification/keras_trainer/single_layer_cnn.py

First attempt at adding ROC AUC to tensorboard. Might explore some other methods too. Supports #42 
Reference: https://github.com/keras-team/keras/issues/6050

Add auc metric to tensorboard. (Plus some minor stuff)

---

annotator-models/trainer/dawid_skene.py

Three small changes in this PR, both related to writing out the results. 
* **fix bug in the error rates** - the code maps the original `y` labels, (e.g. -2, -1, 0, 1, 2) to indices (e.g. 0, 1, 2, 3, 4) for training. After we're done training, we map back to the original labels. I had messed that up so our error rate files had columns that were incorrectly labeled
* **write output as jsonlines** - a good suggestion from @iislucas 
* **rename output field** - from `y_hat_mean` to `{label}_hat_mean` (e.g. `obscene_hat_mean`) for consistency with other fields

Update and fix bug in output of dawid-skene model

---

annotator-models/trainer/dawid_skene.py

[tiny] Small logging improvements

---

hierarchical_attention_research/han_model/HAN_model.py
hierarchical_attention_research/han_model/worker.py

Using for loops to generate rnn cells and separately instantiating forward and backward cells so they don't share parameters.

Updating to new tensorflow handling of rnn cells

---

kaggle-classification/bin/run_keras.sh
kaggle-classification/bin/run_keras_local.sh
kaggle-classification/keras_trainer/model.py
kaggle-classification/keras_trainer/rnn.py

Basic GRU (working on fixed length sequences)

---

kaggle-classification/keras_trainer/rnn.py

Performance has not improved yet - but this is the rough architecture I will proceed with.
For each time step we apply a dense layer to the hidden state, then take the results across all time steps and do a dense + sigmoid to get probabilities. These probabilities are then multiplied with the hidden states from before.

Adding attention to GRUs

---

kaggle-classification/keras_trainer/model.py

* labels are already passed into ModelRunner and so this line should not look for FLAGS.labels

Modelrunner class should not depend on FLAGS

---

kaggle-classification/keras_trainer/cnn_with_attention.py
kaggle-classification/keras_trainer/model.py
kaggle-classification/keras_trainer/rnn.py
kaggle-classification/keras_trainer/single_layer_cnn.py

* Changes model architecture in final dense layer depending on number of labels specified
* Fixes score_auc in the case of a single headed model

Bugfix: specifying the number of labels needs to change the model head

---

kaggle-classification/bin/run_keras.sh
kaggle-classification/bin/run_keras_local.sh
kaggle-classification/keras_trainer/model.py

Adding flag for the comet project name and adding team_name

Making comet project name flaggable

---

kaggle-classification/bin/run_keras.sh
kaggle-classification/keras_trainer/custom_metrics.py
kaggle-classification/keras_trainer/model.py
kaggle-classification/keras_trainer/single_layer_cnn.py

Bunch of minor improvements to the keras model. Wrote for getting results for Dawid-Skene post, but wanted to submit them since I think they are a general improvement.

Minor improvements

---

kaggle-classification/setup.py
kaggle-classification/tf_trainer/base_keras_model.py
kaggle-classification/tf_trainer/dataset_input.py
kaggle-classification/tf_trainer/hparam_config.yaml
kaggle-classification/tf_trainer/run.py
kaggle-classification/tf_trainer/run_ml_engine.sh
kaggle-classification/tf_trainer/text_preprocessor.py
kaggle-classification/tf_trainer/tfrecord_input.py

Also:
- use tf.app.flags
- fix dataset input to use iterator (my last model ate all the memory)

Estimator framework on ml engine

---

experiments/tf_trainer/keras_rnn_model.py
experiments/tf_trainer/run.py
experiments/tf_trainer/run_ml_engine.sh
experiments/tf_trainer/tf_rnn_model.py
experiments/tf_trainer/tfrecord_input.py

Have not started model directory / structure refactor. This is just to get a plain estimator example in.

Estimator RNN Model with Attention

---

experiments/README.md

Adding a simple README with instructions for setting up an environment and running our existing models. Still a work in progress which jjtan and nthain are building collaboratively.

Adding an initial README for model training

---

experiments/setup.py
experiments/tf_trainer/common/model_runner.py
experiments/tf_trainer/keras_gru_attention/model.py
experiments/tf_trainer/keras_gru_attention/run.py
experiments/tf_trainer/keras_gru_attention/run_ml_engine.sh
experiments/tf_trainer/tf_gru_attention/model.py
experiments/tf_trainer/tf_gru_attention/run.py
experiments/tf_trainer/tf_gru_attention/run_ml_engine.sh

- comet ml api key no longer available in logs
- train / eval steps made into flags
- Update packages for ML Engine
- Made TF model have flag for batch size

Small fixes

---

experiments/README.md
experiments/tf_trainer/common/base_keras_model.py
experiments/tf_trainer/common/base_keras_model_test.py

* Fix `run.*.sh` script references in docs, and clarifying and add a few other links and TODOs to the README.
* Add a simple test for the custom ROC-AUC computation.

Add test and improve readme

---

experiments/tf_trainer/common/tfrecord_input.py
experiments/tf_trainer/common/tfrecord_input_test.py
experiments/tf_trainer/keras_cnn/model.py
experiments/tf_trainer/keras_gru_attention/model.py

Fixing accuracy metric

---

.gitignore
experiments/README.md
experiments/WORKSPACE
experiments/tf_trainer/common/BUILD

This provides initial support for Bazel based testing and building.

Initial support for Bazel

---

experiments/tf_trainer/common/base_model.py
experiments/tf_trainer/common/model_trainer.py
experiments/tf_trainer/common/serving_input.py
experiments/tf_trainer/common/text_preprocessor.py
experiments/tf_trainer/common/tfrecord_input.py
experiments/tf_trainer/keras_gru_attention/run.deploy.sh
experiments/tf_trainer/keras_gru_attention/run.py

Please review my changes and suggest any improvements!

Export model

---

experiments/setup.py
experiments/tf_trainer/keras_gru_attention/run.hp.sh
experiments/tf_trainer/keras_gru_attention/run.hyperparameter.sh
experiments/tf_trainer/keras_gru_attention/run.local.sh

Creating shell script for single job (vs hp) + fixing setup.py

---

experiments/tf_trainer/keras_gru_attention/run.deploy.sh
experiments/tf_trainer/keras_gru_attention/run.ml_engine.sh

previous patch was not complete.

Adding missing lines

---

experiments/tf_trainer/common/model_trainer.py

Add profiling to estimator.train.
To see the model profile, in Chrome, go to:
'chrome://tracing'
and Load a timeline-xx.json file.

Add profiler

---

experiments/tf_trainer/keras_cnn/run.py

Fixing the preprocessing for CNNs. They seem to work after this fix.

fixing preprocessor op for cnn

---

model_evaluation/jigsaw_evaluation_pipeline.ipynb
model_evaluation/requirements.txt

Adding evaluation pipeline only

---

experiments/tf_trainer/common/tfrecord_input.py

Dataset input speeding

---

model_evaluation/utils_export/deploy_continuous_model.py

Script to deploy all models contained in a directory. That will be useful when we export several models in a training run.

Deploy models

---

experiments/tf_trainer/common/tfrecord_input.py
experiments/tf_trainer/tf_word_label_embedding/hparam_config.yaml
experiments/tf_trainer/tf_word_label_embedding/model.py
experiments/tf_trainer/tf_word_label_embedding/run.hyperparameter.sh
experiments/tf_trainer/tf_word_label_embedding/run.local.sh
experiments/tf_trainer/tf_word_label_embedding/run.ml_engine.sh
experiments/tf_trainer/tf_word_label_embedding/run.py

Base word label embedding implementation.

Word + Label Embeddings

---

.gitignore
experiments/tf_trainer/tf_word_label_embedding/run.py

I noticed a block of code had been duplicated. Removed.

Removing duplicated lines

---

README.md
experiments/README.md
experiments/tf_trainer/keras_gru_attention/run.ml_engine.sh
experiments/tf_trainer/tf_gru_attention/run.deploy.sh
experiments/tf_trainer/tf_gru_attention/run.ml_engine.sh
model_evaluation/README.md

Updating the README.
Also removing any comet dependencies in experiments/ README.

Add readme

---

experiments/requirements.txt
experiments/setup.py
experiments/tf_trainer/common/model_trainer.py
experiments/tf_trainer/common/tfrecord_input.py
experiments/tf_trainer/common/tfrecord_simple.py
experiments/tf_trainer/tf_hub_classifier/hparam_config.yaml
experiments/tf_trainer/tf_hub_classifier/model.py
experiments/tf_trainer/tf_hub_classifier/run.deploy.sh
experiments/tf_trainer/tf_hub_classifier/run.hyperparameter.sh
experiments/tf_trainer/tf_hub_classifier/run.local.sh
experiments/tf_trainer/tf_hub_classifier/run.ml_engine.sh
experiments/tf_trainer/tf_hub_classifier/run.py

This is a branch of the gru model using the TF Hub sentence encoder.
My quick experiments suggest that this is highly competitive with our existing models.
Achieving 0.985 AUC
This pulls out some implementation classes from common into run.py, but this can be
potentially addressed going forward by generalizing the common code.

TF Hub based classifier

---

experiments/tf_trainer/common/tfrecord_input_test.py

Tests in tfrecord_input_test.py pass.

Updating tf record test

---

.bazelrc
.travis.yml
bazel_0.18.1-linux-x86_64.deb.sha256

Not tested, because needs to be submitted for test IIUC.

Basic travis config for running build and run tests with bazel.

---

experiments/tf_trainer/common/model_trainer.py
experiments/tf_trainer/common/serving_input.py
experiments/tf_trainer/keras_gru_attention/run.py
experiments/tf_trainer/tf_gru_attention/run.py
experiments/tf_trainer/tf_hub_classifier/run.py
experiments/tf_trainer/tf_word_label_embedding/run.py

Remove the signature for the input comment_key int64 feature, making it optional.

Refactor comment_key pass thru feature

---

.travis.yml
experiments/tf_trainer/common/cnn_spec_parser.py

Updated Travis to test both version.

Using Python 3.5 features instead of 3.6 f-strings.

---

experiments/tf_trainer/keras_gru_attention/run.py
experiments/tf_trainer/tf_hub_classifier/run.py

Two more locations that will cause training to fail at the end :-(

Fix references that don't fail until export time.

---

experiments/tf_trainer/common/tfrecord_input.py

Use deep copy to prevent modifing feaures passed in by reference.

Add feature weights to batching branch.

---

experiments/tf_trainer/common/tfrecord_input.py

Does not repeat over the evaluation data.

Moves the dataset repeat higher in the processing chain.

---

experiments/tf_trainer/common/text_preprocessor.py

Address type issue with tokenize function.

---

experiments/tf_trainer/tf_cnn/run.hyperparameter.sh
experiments/tf_trainer/tf_gru_attention/run.hyperparameter.sh
experiments/tf_trainer/tf_hub_classifier/run.hyperparameter.sh
experiments/tf_trainer/tf_word_label_embedding/run.hyperparameter.sh
experiments/tf_trainer/tf_word_label_embedding/run.local.sh

also fixes embedding path/dims in other tf_models

adding run scripts to word_label for other datasets 

---

experiments/tf_trainer/common/BUILD
experiments/tf_trainer/common/text_preprocessor_test.py

Basic tokenization test, using whitespace splitter.

Add initial text preprocessor test.

---

experiments/tf_trainer/common/serving_input.py
experiments/tf_trainer/tf_char_cnn/run.py
experiments/tf_trainer/tf_hub_classifier/run.py

Generalizes shared code for tf hub which uses similar signature.

Fix export for character cnn models.

---

kaggle-classification/requirements.txt

Fixing security vulnerability

---

experiments/tf_trainer/common/basic_gpu_config.yaml
experiments/tf_trainer/common/dataset_config.sh
experiments/tf_trainer/common/p100_config.yaml
experiments/tf_trainer/tf_cnn/run.ml_engine.sh
experiments/tf_trainer/tf_gru_attention/run.ml_engine.sh
experiments/tf_trainer/tf_hub_classifier/model.py
experiments/tf_trainer/tf_hub_classifier/run.ml_engine.sh

Also using cached TF-Hub module.

Updating best hyperparams for tf_cnn, tf_hub, tf_gru models.

---

experiments/tf_trainer/tf_hub_classifier/model.py
experiments/tf_trainer/tf_hub_classifier/myrunlocal.sh
experiments/tf_trainer/tf_hub_classifier/run.hyperparameter.sh
experiments/tf_trainer/tf_hub_classifier/run.local.sh
experiments/tf_trainer/tf_hub_classifier/run.ml_engine.sh

Still training (slowly) now, but already substantially better than without adaptation of weights.

Update to new tf hub model, enable adapting weights.

---

experiments/requirements.txt
experiments/tf_trainer/tf_hub_tfjs/model.py
experiments/tf_trainer/tf_hub_tfjs/run.local.sh
experiments/tf_trainer/tf_hub_tfjs/run.py

Tensorflow JS models are based on tf hub's lite version
of universal sentence encoder, which expects sentences
to be preprocessed into sparse token tensors using the
sentencepiece library.

Add a directory based on stringpiece models for tfjs

---

experiments/tf_trainer/tf_hub_tfjs/run.py

Assign explicit names to the input placeholders.

Rename input placeholder tensors.

---

experiments/tf_trainer/common/dataset_input.py
experiments/tf_trainer/common/tfrecord_input.py
experiments/tf_trainer/common/types.py

Also a step in exploring using pytype (for type-checking in python), and thinking about making a jsonline input class.

fix some comments and types

---

experiments/tools/convert_jsonl_to_tfrecord.py

Forgot FLAGS prefix. 
(pytype found the issue)

fix minor bug in error message printing
