conversationai/conversationai-models

kaggle-classification/run.sh, kaggle-classification/trainer/model.py
This change is a rewrite of the CNN model which adds
* filters of multiple sizes
* dropout during training
I had previously adapted the implementation from one of the examples in the TensorFlow Github repo ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/text_classification_cnn.py)), but JJ pointed out that it only used one filter size. I also found the `tf.layers` API a little confusing. 
JJ pointed me to [this](http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow/) Wild ML CNN tutorial that uses filters of multiple sizes and adds dropout during training. It also uses lower level TensorFlow API's and is a bit easier to read. 
I ran both models on the Kaggle data to predict toxicity and the AUC went up from .76 to …
=> Add filters of varying sizes and dropout to CNN

kaggle-classification/.gitignore, kaggle-classification/README.md, kaggle-classification/requirements.txt, kaggle-classification/run_local.sh, kaggle-classification/trainer/wikidata.py
* Moved local data to a `local_data` directory. 
* Added command line instructions for downloading local data. 
* Made `run_local.sh` use data in `local_data` directory (so it's really totally local)
* Fixed loading code to work in python3 (utf-8 fixes)
* Adds more detailed instructions, and recommends using virtualenv
* Sort the `requirements.txt` because sorting is cool.
=> support python 3, readme tweaks, and run_local fixes

kaggle-classification/bin/run_keras.sh, kaggle-classification/bin/run_keras_local.sh, kaggle-classification/keras_trainer/model.py, kaggle-classification/run_keras_local.sh
- Moves run_keras and run_keras_local to the bin directory
- Replaces model_dir with job_dir
- Adds command line flag to modify hyperparameters
- Adds tensorboard callback
- Adds instruction to run scripts for loading tensorflow
- Changes the directory where models are logged in storage to 'keras_runs'
=> Adding support for hyperparameter flags, tensorboard instructions and general refactoring

kaggle-classification/trainer/model.py
The `bin/run_local` script wasn't running because we had forgotten to add the `learning_rate` parameter to the `bag-of-words` model. 
To test, run `./bin/run_local`
=> [Tiny] Fix bug in bag of words model

annotator-models/bin/ls-jobs
The old functionality of the ls-jobs script printed out all the jobs started that day. I've been finding that what I really want is all _my_ jobs, regardless of what day they started. 
@nthain, @jjtan: This is only a change to the bin/ls-jobs script in the annotator-models directory, but I can change it everywhere if you want.
=> [Tiny] Change ls-jobs to only show user's jobs

annotator-models/trainer/dawid_skene.py
The stopping condition for the dawid-skene code is
```python
if (class_marginals_diff < tol and item_class_diff < tol)
```
That means the sum of the difference in the predicted class distributions need to be less than `tol`. We're running this on hundreds of thousands of examples, so .1 seems far too low.
=> [Tiny] Update default dawid-skene tolerance

annotator-models/trainer/dawid_skene.py
I was looking at this code for another reason and had the insight that at each iteration we were doing this computation, which is the same each time since `counts` is the data that doesn't change.
```python
counts_tiled  = np.stack([counts for a in range(nClasses)], axis=2)
```
So I pulled out that computation and each iteration went down from 1.29 seconds to 1 second on 100k annotations.  Now the vectorized `e_step` is at least the same speed as the embedded for-loop version `e_step_verbose`. I'm sure there are more optimizations to be done, but I'm moving on for now.
=> Speed up vectorized e step 

annotator-models/bin/run, annotator-models/bin/run_local, annotator-models/trainer/dawid_skene.py
The output of running the dawid-skene trainer is:
* the predicted labels - A file with the per-item predictions, (eg `predictions_obscene_100000.json`) that contains the comment id (`_unit_id`), the mean score from the original data (`obscene_mean`) and predicted probability for each class (`obscene_hat_0`, `obscene_hat_1`).
* the predicted error rates - A file that has the per-rater error rates. Instead of including the full `nClasses x nClasses` error rate matrix, I'm only including the values on the diagonal. I got myself turner around yesterday, because the diagonal error rates are actually accuracy rates (i.e. probability of correctly predicting class k if the true class was k).
This change improves these outputs by 1) updating the column names of the diagonal error rates to per …
=> Improve output of the dawid-skene trainer 

kaggle-classification/bin/run_keras.sh, kaggle-classification/bin/run_keras_local.sh, kaggle-classification/keras_trainer/model.py
This change renames the `--validation_path` flag to `--test_path` for the keras model. It turns out that data was not used for validation during training. It's only used to calculate the final AUC score. Which is as it should be, but we should rename the flag to reflect that.
=> Rename validation_path flag to test_path

kaggle-classification/keras_trainer/model.py
This change adds an optional `--labels` flag to the keras ModelRunner. The default labels are the same `'toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate'` that we were using before. But now you can specify different labels like
```shell
python -m keras_trainer.model --labels=toxic_score,insult
```
=> Add flag to adjust labels to run on

annotator-models/trainer/dawid_skene.py
This change adds smoothing to the dawid skene implementation. 
I was noticing that many of the dawid-skene predictions were very close to 0, i.e. for comment i, p(class = j | annotations, worker_error_rates) was often 0. This is the equation for how we calculate this probability given the model: 
The z's are the predicted labels and the thetas are the worker error rates. If a worker's error rate is zero for one class, which it would be if they never rated any examples with that class, we would never predict that class. It's a standard trick to add pseudo counts to avoid this problem. I've run results with pseudo counts of 3 and saw results improve on hand labeled examples.
=> Add smoothing for error rates

experiments/tf_trainer/common/serving_input.py, experiments/tf_trainer/common/text_preprocessor.py, experiments/tf_trainer/common/tfrecord_input.py, experiments/tf_trainer/keras_gru_attention/run.deploy.sh, experiments/tf_trainer/keras_gru_attention/run.py
Please review this.
There is one "ugly" workaround. 
The tokenizer is different for training and for serving. Indeed, for training the tokenizer will be used within a map function and then processes one example at a time, whereas for serving the tokenizer needs to process an entire batch.
Therefore, in run.py, I initialize twice the tokenizer. It does not seem a big deal to me but I acknowledge it could be improved. I tried to merge (by doing all per batch or per example) but unsuccessfully.
Might be a TODO or a github issue.
Let me know your thoughts.
=> Adding serving function for tf_records with unknown batch size.

experiments/setup.py, experiments/tf_trainer/common/tfrecord_input.py, experiments/tf_trainer/common/tfrecord_input_test.py
Adds a default value to tfrecord_input so that not all labels must be present in every record.
Fixes tfrecord_input_test which had previously been broken (and adds test for default values).
=> Fix tfrecord input

experiments/tf_trainer/common/tfrecord_input.py
As mentioned earlier, this should solve the problem of rank for iterator.
This problem happened when there was only 1 word in a sentence. In this case, tf.squeeze would turn the tensor into a scalar.
So, we wanted a sentence of rank 1 (shape = (sequence_length,)), but got a scalar of rank 0.
=> Fixing bug input rank

experiments/tf_trainer/common/serving_input.py, experiments/tf_trainer/common/text_preprocessor.py, experiments/tf_trainer/common/tfrecord_input.py, experiments/tf_trainer/keras_gru_attention/run.py, experiments/tf_trainer/tf_gru_attention/run.py, model_evaluation/jigsaw_evaluation_pipeline.ipynb
This review does:
- Set as only option a python tokenizer for training
- Change the serving function to expect a list of words.
- Change the evaluation notebook accordingly.
Tests run:
- Training of keras model on Glove + Evaluation in the notebook
- Training of tf_model (serving function for tf left as a todo).
This pr included many changes. Please let me know if new design makes sense!
=> Enforcing nltk tokenizer

experiments/tf_trainer/common/model_trainer.py, experiments/tf_trainer/common/text_preprocessor.py, experiments/tf_trainer/common/tfrecord_input.py, experiments/tf_trainer/tf_gru_attention/run.py, model_evaluation/jigsaw_evaluation_pipeline.ipynb
Adding the serving function for tf-part.
2 points:
- In model_trainer, I had to rewrite the forward_features function to workaround a bug. I created an internal bug to update the function.
- is_trainable is void for a keras model. I can explain why in our meeting but it might require some work to get it fixed. Maybe we should raise an exception when trainable=True and model=keras? Not sure where to insert that though.
=> Serving for tf

experiments/requirements.txt, experiments/tf_trainer/common/model_trainer.py, experiments/tf_trainer/common/tfrecord_input.py, experiments/tf_trainer/keras_gru_attention/run.hyperparameter.sh, experiments/tf_trainer/keras_gru_attention/run.ml_engine.sh, experiments/tf_trainer/tf_gru_attention/run.hyperparameter.sh, experiments/tf_trainer/tf_gru_attention/run.ml_engine.sh, experiments/tf_trainer/tf_gru_attention/run.py
This commit aims at correcting this bug: https://github.com/tensorflow/tensorflow/issues/19062.
The way to make the correction is to upgrade to tf==1.10 and to use train_and_evaluate.
Using train_and_evaluate removes the flexibility around the training loop. In particular, it is not easy anymore to include comet. We have removed it for now and could potentially be re-introduced via training_hooks.
=> Train and evaluate

model_evaluation/utils_export/dataset.py
When initializing a Model instance, we give model_names (can be seen as names of different versions of this model). We will then call concurrently all the models for CMLE prediction jobs.
This will trigger an error if there are more than 7 versions due to default quotas. This is why I raise an Exception when creating model with too many versions.
=> Adding quota when creating models

model_evaluation/jigsaw_evaluation_pipeline.ipynb, model_evaluation/utils_export/dataset.py, model_evaluation/utils_export/dataset_test.py, model_evaluation/utils_export/utils_cloudml.py
Restructuring the code to add one feature "Loading". 
Feature description:
When we call the method dataset.add_model_prediction_to_data(model) we now have an extra argument 'recompute_predictions'.
If set to False, we reload past prediction instead of rerunning the entire pipeline.
Design changes:
- Clarification of the file names. A dataset has now a 'dataset_dir' where all the files will be saved (input_tf_records and output_predictions).
- Adding good tests for the entire pipeline in dataset_test.py
The rest are minor changes to keep a clean flow.
Thank you for the review.
=> Adding loading option

annotator-models/requirements.txt, attention-tutorial/requirements.txt, experiments/requirements.txt, kaggle-classification/requirements.txt, model_evaluation/requirements.txt
This change just updates the requests package to the minimum level to address the
security alerts. I tested it only minimally, but expect that it should be fine.
=> Address security alerts for request package

experiments/tf_trainer/common/base_keras_model.py, experiments/tf_trainer/common/base_keras_model_test.py, experiments/tf_trainer/common/base_model.py, experiments/tf_trainer/common/dataset_input.py, experiments/tf_trainer/common/model_trainer.py, experiments/tf_trainer/common/tfrecord_input_test.py, experiments/tf_trainer/common/types.py, experiments/tools/convert_csv_to_tfrecord.py
Note that every code file should have the corresponding google copyright header. I'm adding a bunch here.
=> Add missing copyright headers to files

experiments/tf_trainer/common/tfrecord_input.py, experiments/tf_trainer/common/tfrecord_input_test.py, experiments/tf_trainer/tf_gru_attention/run.local.sh
This PR allows for labels to have different dtypes via a new flag "label_dtypes". This can be used to specify the dtypes of each label as being either "float" or "int".
It also fixes:
- typo in a local run script (sever_toxicity -> severe_toxicity)
- inconsistent quoting in tfrecord_input.py
This branches from msushkov's commit "Adding test for int64 label" and so also includes unmerged changes from that branch.
=> Add label dtypes

experiments/tf_trainer/common/dataset_config.sh, experiments/tf_trainer/common/tfrecord_input.py, experiments/tf_trainer/keras_cnn/run.ml_engine.sh, experiments/tf_trainer/keras_gru_attention/run.hyperparameter.sh, experiments/tf_trainer/keras_gru_attention/run.ml_engine.sh, experiments/tf_trainer/tf_char_cnn/run.deploy.sh, experiments/tf_trainer/tf_char_cnn/run.hyperparameter.sh, experiments/tf_trainer/tf_char_cnn/run.local.sh, experiments/tf_trainer/tf_char_cnn/run.ml_engine.sh, experiments/tf_trainer/tf_cnn/run.deploy.sh, experiments/tf_trainer/tf_cnn/run.hyperparameter.sh, experiments/tf_trainer/tf_cnn/run.local.sh, experiments/tf_trainer/tf_cnn/run.ml_engine.sh, experiments/tf_trainer/tf_gru_attention/run.deploy.sh, experiments/tf_trainer/tf_gru_attention/run.hyperparameter.sh, experiments/tf_trainer/tf_gru_attention/run.local.sh, experiments/tf_trainer/tf_gru_attention/run.ml_engine.sh, experiments/tf_trainer/tf_hub_classifier/run.deploy.sh, experiments/tf_trainer/tf_hub_classifier/run.hyperparameter.sh, experiments/tf_trainer/tf_hub_classifier/run.local.sh, experiments/tf_trainer/tf_hub_classifier/run.ml_engine.sh, experiments/tf_trainer/tf_word_label_embedding/run.hyperparameter.sh, experiments/tf_trainer/tf_word_label_embedding/run.local.sh, experiments/tf_trainer/tf_word_label_embedding/run.ml_engine.sh
This PR refactors the paths for the run scripts and points them to the path for the new cloud project (please refer to the e-mail I sent and respond there if there are any issues or concerns). It also reduces the default batch size of the models so that you don't by default run into OOM error when training on ML engine. 
In a future PR, I will refactor so that we will finally have one run script that can run all of the models instead of having a separate run script per model.
=> Refactoring run scripts and moving paths to new project

model_evaluation/utils_export/dataset.py, model_evaluation/utils_export/utils_cloudml.py, model_evaluation/utils_export/utils_cloudml_test.py, model_evaluation/utils_export/utils_tfrecords_test.py
Adding better messages for the problems highlighted [here](https://github.com/conversationai/conversationai-models/issues/217#event-2029346108).
It will show better message in the case when:
- User gives a bad input signature (feature_keys_spec of `Model`). It leads to an empty prediction file.
- User gives a bad output signature (prediction_keys of `Model`). It leads to being unable to parse the JSON back.
I also added some tests for this part of the code.
=> Adding better error messages when using batch prediction

experiments/tools/convert_csv_to_tfrecord.py
Pandas sometimes interprets strings of numbers as floats which raises issues when encoding to a byte_list. This ensures that the text is treated as a string.
=> casting to avoid errors from type ambiguity
